services:
  redditarr:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: redditarr
    ports:
      - "${PORT:-8481}:80"
    volumes:
      # Store application state and database
      - ./appdata:/config
      # Store downloaded media files
      - ./media:/media
      # For development only - hot reload
      - ./app:/app/app
      - ./static:/app/static
    environment:
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_USERNAME
      - REDDIT_PASSWORD
      - TZ=${TZ:-UTC}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 60s     # Check every minute
      timeout: 30s      # Allow more time for health check
      retries: 5        # More retries before marking unhealthy
      start_period: 30s # Give more time for initial startup
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-1G}
        reservations:
          memory: ${MEMORY_MIN:-256M}